version: "3.3"

services:
  office-employee-front:
    container_name: office-employee-front
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./office-employee-front:/usr/src/app/office-employee-front
      - /usr/src/app/office-employee-front/node_modules
      - /usr/src/app/office-employee-front/.next
    ports:
      - 3000:3000
